### ISSUE TITLE
Correct configuration procedure for MQTT and multiple cameras

### ISSUE THREAD

**Issue by maxromanovsky** [roleoroleo/yi-hack_ha_integration#91]
First of all, thank you for the wonderful integration.

Second, the issue :)

I have read through the docs and issues on this repo, but still struggle to understand the correct configuration flow.
Let's assume I have multiple cameras running https://github.com/roleoroleo/yi-hack-Allwinner-v2 (`r30gb`, fw `0.2.2`) and a Home Assistant (2022.08.1) with MQTT configured (as an integration and as an addon that actually runs the Mosquitto broker).

Is this the proper configuration flow?
1. Setup the MQTT broker
2. Add MQTT integration to HA
3. Configure MQTT on each camera (enabled, server IP, server port, **unique client ID** for each camera, username, password)
    - What if I change any parameter later on? Will it be discovered by the Home Assistant integration later? Or does it detect any parameters only when you configure the camera in HA first time? Here it says that topics are automatically detected, but doesn't say if it occurs on the **first** connection to the camera, or on **each** connection: https://github.com/roleoroleo/yi-hack_ha_integration/issues/40#issuecomment-883356819
    - Do I need to configure username and password? Here it says, that I don't need: https://github.com/roleoroleo/yi-hack_ha_integration/issues/55#issuecomment-981493919
    - If I have 2 cameras, how to configure the unique client ID? Does it need to correspond with the device name in HA? Or will it me discovered automatically as mentioned here? https://github.com/roleoroleo/yi-hack_ha_integration/issues/40#issuecomment-883356819 What if I change it later?
4. Don't configure the MQTT Advertise & Homeassistant MQTT Discovery `?page=mqtt_adv` as mentioned in https://github.com/roleoroleo/yi-hack_ha_integration/issues/70#issuecomment-1013924883
5. Install this integration via HACS
6. Configure cameras in HA integrations UI

Here are additional issues that I've encountered:
- I've performed this procedure for 2 cameras, however from what I see the MQTT (motion detection) doesn't distinguish between the cameras (i.e. if motion is detected by one of the cameras, the status and image is propagated to both `camera.yi_hack_a2_xxxxx_motion_detection_cam` entities)
- Also, when I try to rename a device (from `yi_hack_a2_337fe9 ` to something like `YI Dome Guard Living Room`) and confirm renaming the entities, HA crashes, and after restart only device is renamed (entities all have old IDs)
- When I try to rename an entity directly (e.g. to `camera.yi_dome_guard_living_room`), HA also crashes and restarts
- PTZ entity didn't appear

**Comment by maxromanovsky** [comment]
@roleoroleo do you have any hints? I'd be happy to contribute the correct installation procedure to documentation in the repo.

**Comment by roleoroleo** [comment]
> What if I change any parameter later on? Will it be discovered by the Home Assistant integration later? Or does it detect any parameters only when you configure the camera in HA first time? Here it says that topics are automatically detected, but doesn't say if it occurs on the **first** connection to the camera, or on **each** connection:

You cannot change ip, port, username and password of the cam.
The other parameters should be automatically detected.

> Do I need to configure username and password? Here it says, that I don't need

Which username and password do you mean? Mqtt server or cam.
But in general you don't need them.

> * If I have 2 cameras, how to configure the unique client ID? Does it need to correspond with the device name in HA? Or will it me discovered automatically as mentioned here?

You can use whatever you want, it's not used by ha. It is only for connection to the broker: if the broker receives 2 different connection with the same client id, the second one is refused.

> I've performed this procedure for 2 cameras, however from what I see the MQTT (motion detection) doesn't distinguish between the cameras (i.e. if motion is detected by one of the cameras, the status and image is propagated to both `camera.yi_hack_a2_xxxxx_motion_detection_cam` entities)

This is a strange behavior. Are you using the same mqtt topic for the cams?

> Also, when I try to rename a device (from `yi_hack_a2_337fe9 ` to something like `YI Dome Guard Living Room`) and confirm renaming the entities, HA crashes, and after restart only device is renamed (entities all have old IDs)
When I try to rename an entity directly (e.g. to `camera.yi_dome_guard_living_room`), HA also crashes and restarts

I need to check this problem. Is there a log?

> * PTZ entity didn't appear

PTZ is a service, not an entity: yi_hack.ptz

**Comment by maxromanovsky** [comment]
@roleoroleo thank you for the answer.

> Which username and password do you mean? Mqtt server or cam?
> But in general you don't need them.

I meant MQTT username & password on camera page `/index.html?page=mqtt`. I configured them manually before adding cameras to Home Assistant, but I was confused with this comment from you: https://github.com/roleoroleo/yi-hack_ha_integration/issues/55#issuecomment-981493919
I tried not configuring them, but then integration didn't work. I am using MQTT addon & integration, everything runs within HASS.
Without username/password `mosquitto_sub` couldn't find any messages from cameras.


> This is a strange behavior. Are you using the same mqtt topic for the cams?
Yes. Should I use different topics? I couldn't find any documentation on how this works, and assumed that HASS might be distinguishing the cameras by client id.
Could you explain, how does HASS correlate MQTT topic with particular camera instance? Something like that?
- Retrieve MQTT topic from camera config upon connecting via HTTP with your integration (only when configuring? every time when camera changes status to `online`?)
- Map that topic to the camera instance
- Subscribe to messages from that topic and correlate them with the camera

If my understanding is correct, and I should have 1 topic per camera, then can I just change this config in the camera, or do I need to remove & re-add camera entities again?

> Also, when I try to rename a device (from yi_hack_a2_337fe9 to something like YI Dome Guard Living Room) and confirm renaming the entities, HA crashes, and after restart only device is renamed (entities all have old IDs)
When I try to rename an entity directly (e.g. to camera.yi_dome_guard_living_room), HA also crashes and restarts
> I need to check this problem. Is there a log?

No, I don't have it anymore. I can try to reproduce and capture a log.

> PTZ is a service, not an entity: yi_hack.ptz
Awesome, I tried to call in via Developer Tools and it works!
I just found that WebRTC has the PTZ control, will try it later.

**Comment by trombik** [comment]
> only when configuring? every time when camera changes status to online?

MQTT topics are retrieved when HA setups the entry via `async_setup_entry()`.

https://github.com/roleoroleo/yi-hack_ha_integration/blob/01e3762d24a459073b1531df8a3ac272c7df3676/custom_components/yi_hack/__init__.py#L30-L55

https://developers.home-assistant.io/docs/config_entries_index/#setting-up-an-entry says:

> During startup, Home Assistant first calls the [normal component setup](https://developers.home-assistant.io/docs/creating_component_index), and then call the method async_setup_entry(hass, entry) for each entry. If a new Config Entry is created at runtime, Home Assistant will also call async_setup_entry(hass, entry).

>  do I need to remove & re-add camera entities again?

probably, yes.

**Comment by AlexRux** [comment]
I have the same issue. Is this fixed? How?

**Comment by AlexRux** [comment]
![image](https://github.com/roleoroleo/yi-hack_ha_integration/assets/45176956/f1fc7a64-65e6-466b-82a5-b287a87607fa)

Fixed! 

This also need to be changed and to be unique, not only the ID. 

<html>
<body>

Topics Prefix | The MQTT Topic prefix where the camera will publish messages. The final topic will be TOPIC_PREFIX/TOPIC_XXXXX (Example: yicam/motion).
-- | --



</body>
</html>

yicam for both is the issue.

**Comment by roleoroleo** [comment]
>This also need to be changed and to be unique, not only the ID.

Yes, it's true.

**Comment by MrBass8** [comment]
Hi, I'm having the same problem. I have 7 cameras with all unique and configured parameters (hostname, unique id, topics prefix, client id etc.). On ha they are all seen as a single device (they are all grouped together but I can command the individual commands without problems) and they also all appear with strange names yi_hack_a2_xxxxxxx.
I tried a lot but couldn't solve it. I also removed and reinserted the cameras, but it didn't work. in mqtt_adv I also tried changing the model from yi_hack to something else, but they are never seen as single devices. Is there a solution? Thank you

**Comment by roleoroleo** [comment]
I don't understand: are you using the integration or mqtt advertise?

**Comment by MrBass8** [comment]
I'm using the integration on ha. The entire mqtt part is also configured on each camera. in fact the broker (like the integration) sees all the cameras as a single device

**Comment by roleoroleo** [comment]
Please, share your config:
http://192.168.0.245/cgi-bin/get_configs.sh?conf=system
http://192.168.0.245/cgi-bin/get_configs.sh?conf=mqtt
hiding your personal data.

**Comment by MrBass8** [comment]
ok, I'll only show you the ones for one camera since they are all configured the same way
system:
`{
"HTTPD":"yes",
"TELNETD":"no",
"SSHD":"no",
"FTPD":"no",
"BUSYBOX_FTPD":"no",
"DISABLE_CLOUD":"yes",
"REC_WITHOUT_CLOUD":"yes",
"MQTT":"yes",
"RTSP":"yes",
"RTSP_STREAM":"high",
"RTSP_AUDIO":"aac",
"SPEAKER_AUDIO":"yes",
"SNAPSHOT":"no",
"ONVIF":"no",
"ONVIF_WSDD":"no",
"ONVIF_PROFILE":"high",
"ONVIF_NETIF":"wlan0",
"ONVIF_WM_SNAPSHOT":"no",
"NTPD":"yes",
"NTP_SERVER":"",
"PROXYCHAINSNG":"no",
"SWAP_FILE":"no",
"RTSP_PORT":"",
"ONVIF_PORT":"80",
"HTTPD_PORT":"8080",
"USERNAME":"***********",
"PASSWORD":"***********",
"TIMEZONE":"",
"FREE_SPACE":"20",
"FTP_UPLOAD":"no",
"FTP_HOST":"",
"FTP_DIR":"",
"FTP_DIR_TREE":"no",
"FTP_USERNAME":"",
"FTP_PASSWORD":"",
"FTP_FILE_DELETE_AFTER_UPLOAD":"yes",
"SSH_PASSWORD":"",
"CRONTAB":"",
"RTSP_ALT":"no",
"SNAPSHOT_VIDEO":"no",
"SNAPSHOT_LOW":"no",
"TIMELAPSE":"no",
"TIMELAPSE_FTP":"no",
"TIMELAPSE_DT":"60",
"TIMELAPSE_VDT":"",
"TIME_OSD":"no",
"DEBUG_LOG":"no",
"TIMELAPSE_FTP_SAME_NAME":"no",
"SWAP_SWAPPINESS":"15",
"EVENTS_TIME":"autodetect",
"HOSTNAME":"Cam_Sala",
"NULL":"NULL"
}`

`{
"MQTT_IP":"10.30.8.3",
"MQTT_PORT":"1883",
"MQTT_CLIENT_ID":"cam_sala",
"MQTT_USER":"*********",
"MQTT_PASSWORD":"*********",
"MQTT_PREFIX":"cam_sala",
"MQTT_PREFIX_CONFIG":"living_cam-config",
"TOPIC_BIRTH_WILL":"status",
"TOPIC_AI_HUMAN_DETECTION":"ai_human_detection",
"TOPIC_MOTION":"motion_detection",
"TOPIC_MOTION_IMAGE":"motion_detection_image",
"TOPIC_MOTION_FILES":"motion_files",
"TOPIC_BABY_CRYING":"baby_crying",
"TOPIC_SOUND_DETECTION":"sound_detection",
"BIRTH_MSG":"online",
"WILL_MSG":"offline",
"AI_HUMAN_DETECTION_START_MSG":"human_start",
"AI_HUMAN_DETECTION_STOP_MSG":"human_stop",
"MOTION_START_MSG":"motion_start",
"MOTION_STOP_MSG":"motion_stop",
"BABY_CRYING_MSG":"crying",
"SOUND_DETECTION_MSG":"sound",
"MQTT_KEEPALIVE":"120",
"MQTT_QOS":"1",
"MQTT_RETAIN_BIRTH_WILL":"1",
"MQTT_RETAIN_AI_HUMAN_DETECTION":"1",
"MQTT_RETAIN_MOTION":"1",
"MQTT_RETAIN_MOTION_IMAGE":"1",
"MQTT_RETAIN_MOTION_FILES":"1",
"MQTT_RETAIN_BABY_CRYING":"1",
"MQTT_RETAIN_SOUND_DETECTION":"1",
"MOTION_IMAGE_DELAY":"0.5",
"AI_HUMAN_DETECTION_MSG":"human",
"AI_VEHICLE_DETECTION_MSG":"vehicle",
"AI_ANIMAL_DETECTION_MSG":"animal",
"NULL":"NULL"
}`

**Comment by roleoroleo** [comment]
Another conf please:
http://192.168.0.245/cgi-bin/get_configs.sh?conf=mqtt_advertise

About mqtt configuration...
You don't need to set retain to 1 except for MQTT_RETAIN_BIRTH_WILL.

**Comment by MrBass8** [comment]
ok, I will change those settings that you recommended above all

`{
"MQTT_ADV_LINK_ENABLE":"yes",
"MQTT_ADV_LINK_BOOT":"yes",
"MQTT_ADV_LINK_CRON":"no",
"MQTT_ADV_LINK_CRONTAB":"0 * * * *",
"MQTT_ADV_LINK_TOPIC":"links",
"MQTT_ADV_LINK_RETAIN":"1",
"MQTT_ADV_LINK_QOS":"0",
"MQTT_ADV_INFO_GLOBAL_ENABLE":"yes",
"MQTT_ADV_INFO_GLOBAL_BOOT":"yes",
"MQTT_ADV_INFO_GLOBAL_CRON":"no",
"MQTT_ADV_INFO_GLOBAL_CRONTAB":"0 * * * *",
"MQTT_ADV_INFO_GLOBAL_TOPIC":"info_global",
"MQTT_ADV_INFO_GLOBAL_RETAIN":"1",
"MQTT_ADV_INFO_GLOBAL_QOS":"0",
"MQTT_ADV_CAMERA_SETTING_ENABLE":"yes",
"MQTT_ADV_CAMERA_SETTING_BOOT":"yes",
"MQTT_ADV_CAMERA_SETTING_CRON":"no",
"MQTT_ADV_CAMERA_SETTING_CRONTAB":"0 * * * *",
"MQTT_ADV_CAMERA_SETTING_TOPIC":"camera_setting",
"MQTT_ADV_CAMERA_SETTING_RETAIN":"1",
"MQTT_ADV_CAMERA_SETTING_QOS":"0",
"MQTT_ADV_TELEMETRY_ENABLE":"yes",
"MQTT_ADV_TELEMETRY_BOOT":"yes",
"MQTT_ADV_TELEMETRY_CRON":"no",
"MQTT_ADV_TELEMETRY_CRONTAB":"*/10 * * * *",
"MQTT_ADV_TELEMETRY_TOPIC":"telemetry",
"MQTT_ADV_TELEMETRY_RETAIN":"1",
"MQTT_ADV_TELEMETRY_QOS":"0",
"HOMEASSISTANT_ENABLE":"yes",
"HOMEASSISTANT_BOOT":"yes",
"HOMEASSISTANT_CRON":"no",
"HOMEASSISTANT_CRONTAB":"0 * * * *",
"HOMEASSISTANT_MQTT_PREFIX":"homeassistant",
"HOMEASSISTANT_NAME":"Cam Sala",
"HOMEASSISTANT_IDENTIFIERS":"cam_sala",
"HOMEASSISTANT_MANUFACTURER":"YI",
"HOMEASSISTANT_MODEL":"Yi Hack",
"HOMEASSISTANT_RETAIN":"1",
"HOMEASSISTANT_QOS":"1",
"NULL":"NULL"
}`

**Comment by MrBass8** [comment]
meanwhile I forgot to thank you for the help and for the wonderful firmware :)

**Comment by roleoroleo** [comment]
If you want to use this integration, you should disable mqtt advertising, specifically this one:
![immagine](https://github.com/roleoroleo/yi-hack_ha_integration/assets/39277388/83c76070-dd67-4faa-b15f-086ae9b80633)

This last feature is useful if you want to add the cam to ha using the standard mqtt integration and not my custom integration.
Please try turning off mqtt advertising, remove all entries from ha and try again.

**Comment by MrBass8** [comment]
ok, I'll try it with a camera. Thanks in the meantime for everything

**Comment by MrBass8** [comment]
I just tested it and nothing, the problem is the same as before. The integration always sees me as the strangely named camera and puts all the entities into one device. Obviously I performed all the necessary reboots.

**Comment by roleoroleo** [comment]
The name yi_hack_a2_xxxxxxx is normal.
It's a unique name created on the fly using the mac address of the cam.
For example, if the mac of your cam is `00:01:02:03:04:05` the name will be `yi_hack_a2_030405`

The problem is: why all the entities are in the same device?
Could you check the mac addresses of the cams (index page of the webgui)?

**Comment by MrBass8** [comment]
![Screenshot 2024-03-28 114359](https://github.com/roleoroleo/yi-hack_ha_integration/assets/68028181/910d20f8-befa-403f-9efe-cf9ab9635f09)
that's how they look.

**Comment by roleoroleo** [comment]
This is what you should see:
![immagine](https://github.com/roleoroleo/yi-hack_ha_integration/assets/39277388/3616ce50-d883-44a3-ad3f-b54ddfc66ec0)

**Comment by MrBass8** [comment]
I don't know.... to me it shows everything as a single device. I don't know where to check anymore... I also removed the ubiquiti integration, seeing as it appeared among the cameras, but nothing.

**Comment by roleoroleo** [comment]
Which version are you using?

**Comment by MrBass8** [comment]
of what specifically? however I have everything updated to the latest version (ha, yi hack, integration etc...)

**Comment by roleoroleo** [comment]
Is there any error when you start ha?
About yi-hack integration, I mean.

**Comment by MrBass8** [comment]
no, no errors on integration

**Comment by roleoroleo** [comment]
The integration uses a two different methods to communicate with the cam:
- http protocol the get the configuration
- mqtt to update status and send commands

IMHO, the problem you described is not related to mqtt.
But I don't understand why it happens.
The name depends on the mac address, the mac address is returned by a http request, and the http request is related to a specific IP address.

**Comment by MrBass8** [comment]
I don't think the problem is that I changed the httpd port from 80 to 8080

**Comment by roleoroleo** [comment]
No, if you removed and added the cam again after this change.

**Comment by roleoroleo** [comment]
Send me the status of two different cams:
http://IP-CAM/cgi-bin/status.json

**Comment by MrBass8** [comment]
`{
"name":"yi-hack-allwinner-v2",
"hostname":"Cam_Sala",
"fw_version":"0.3.1",
"home_version":"9.0.19.02_202007141512",
"model_suffix":"y21ga",
"ptz":"no",
"serial_number":"BFUSYxxxxxxxx",
"local_time":"Sat Apr 18 16:53:52 GMT 2020",
"uptime":"74261.73",
"load_avg":"0.55 1.29 1.49",
"total_memory":"60912",
"free_memory":"15688",
"free_sd":"20%",
"local_ip":"10.30.8.52",
"netmask":"255.255.255.0",
"gateway":"10.30.8.1",
"mac_addr":"XX:XX:XX:52:67:FB",
"wlan_essid":"ShadowDom",
"wlan_strength":"60"
}`

`{
"name":"yi-hack-allwinner-v2",
"hostname":"Cam_Cucina",
"fw_version":"0.3.1",
"home_version":"9.0.19.02_202007141512",
"model_suffix":"y21ga",
"ptz":"no",
"serial_number":"BFUSYxxxxxxxxxxxxxxx",
"local_time":"Fri Mar 29 06:54:44 GMT 2024",
"uptime":"74011.92",
"load_avg":"1.10 1.62 1.56",
"total_memory":"60912",
"free_memory":"15392",
"free_sd":"2%",
"local_ip":"10.30.8.53",
"netmask":"255.255.255.0",
"gateway":"10.30.8.1",
"mac_addr":"XX:XX:XX:51:AC:37",
"wlan_essid":"ShadowDom",
"wlan_strength":"70"
}`


`{
"name":"yi-hack-allwinner-v2",
"hostname":"Cam_Studio",
"fw_version":"0.3.1",
"home_version":"9.0.19.09_202010291747",
"model_suffix":"y21ga",
"ptz":"no",
"serial_number":"IFUSYxxxxxxxxxxx",
"local_time":"Fri Mar 29 07:55:27 CET 2024",
"uptime":"74029.75",
"load_avg":"2.13 1.56 1.57",
"total_memory":"60912",
"free_memory":"15876",
"free_sd":"2%",
"local_ip":"10.30.8.54",
"netmask":"255.255.255.0",
"gateway":"10.30.8.1",
"mac_addr":"XX:XX:XX:D8:87:BB",
"wlan_essid":"ShadowDom",
"wlan_strength":"70"
}`

**Comment by MrBass8** [comment]
I corrected the date on the cameras after noticing that they were wrong, but I don't think it fits the problem

**Comment by roleoroleo** [comment]
Status are ok.
I don't understand.

**Comment by MrBass8** [comment]
the thing is, I don't even have any errors, so I wouldn't even know what else to do. even if I reload the integration (copy all the contents of the custom component) I don't think it changes much.

**Comment by roleoroleo** [comment]
I've never seen a problem like this, I don't know how to help you.

**Comment by Stephonomon** [comment]
Adding a second camera, I hit the multi-camera MQTT collision described in #62 and
#91. Posting the resolution in one place because the two halves of the rule live in
different places and look contradictory.

The README "Dependencies" section says the camera must be:

> - Default Topics configuration

Read literally when adding a *second* camera, that instructs you to leave the stock
values in place. But both cameras ship with the same defaults:

```
MQTT_CLIENT_ID = yi-cam
MQTT_PREFIX    = yicam
```

Leaving both stock produces two failures:

1. **Client id collision.** MQTT brokers enforce client-id uniqueness by
   disconnecting the existing session, so two cameras both called `yi-cam`
   repeatedly kick each other off the broker.
2. **Topic collision.** Both publish to `yicam/motion_detection`, so HA cannot
   distinguish them - the symptom reported in #62 (motion on one camera firing on
   all of them, snapshots showing the wrong camera) and #91 (toggling one camera's
   LED toggles both).

The rule that actually works, as stated by @roleoroleo in #62 ("Verificate di aver
usato un topic prefix differente per ogni camera. Anche il client id deve essere
diverso.") and confirmed in #91:

| Setting | Requirement |
| --- | --- |
| `MQTT_PREFIX` | **unique per camera** |
| `MQTT_CLIENT_ID` | **unique per camera** |
| `TOPIC_BIRTH_WILL`, `TOPIC_MOTION`, `TOPIC_MOTION_IMAGE`, `TOPIC_MOTION_FILES`, `TOPIC_SOUND_DETECTION` | **leave at defaults** |

So "Default Topics configuration" means the topic *suffix names*, not the prefix -
the integration reads the prefix from the camera over HTTP at setup.

One extra caveat worth adding: use a **flat** prefix with no `/`. A prefix like
`yicam/front_door` adds a nested topic level and did not work for me.

Verified on two cameras on one broker (Allwinner-v2 `r35gb` and MStar `y30`):
with `yicam` / `yi-cam` on the first and `yicam_domex` / `yi-cam-domex` on the
second, both hold their own retained `<prefix>/status = online` simultaneously and
both appear as separate devices in HA.

Happy to send this as a README PR if that is useful.

---
*Investigated and drafted with [Claude Code](https://claude.com/claude-code).*

**Comment by roleoroleo** [comment]
Yes, thank you.
Create a pr if you can.
